apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath
spec:
  storageClassName: manual    # Debe coincidir con lo indicado en el pv
  accessModes:
    - ReadWriteOnce           # Igual, debe coincidir con lo indicado en el pv
  resources:
    requests:
      storage: 100Mi
